spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_example?useLegacyDatetimeCode=false&serverTimezone=UTC
    username: springuser
    password: ThePassword

  jpa:
    hibernate:
#      todo play with this (create/ create or drop), for prod better to create once
      ddl-auto: create-drop
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        default_schema: das
#        jdbc:
#          lob:
#            non_contextual_creation: true
#  profiles:
#    active: ${ENVIRONMENT:dev}
#  flyway:
#    baseline-on-migrate: true
